[package]
name = "beep-server"
edition = "2024"
version = "0.1.0"
authors = ["nathael <pro.nathaelbonnal@gmail.com>"]
license = "Apache-2.0"

[dependencies]
clap = { version = "4.5.51", features = ["env", "derive"] }
